import React, { createContext, useContext, useState, useEffect } from "react";

const translations = {
    en: {
        settings: "Settings",
        language: "Language",
        theme: "Theme",
        logout: "Logout",
        light: "Light",
        dark: "Dark",
        login: "Login",
        about: "About",
        dashboard: "Dashboard",
        createAccount: "Create Account",
        decisionSupportSystem: "DECISION SUPPORT SYSTEM",
        professionalDecisionSupport: "Professional Decision Support System Based on",
        analyticHierarchyProcess: "Analytic Hierarchy Process",
        goToDashboard: "Go to Dashboard",
        welcome: "Welcome",
        myProjects: "My Projects",
        createNewProject: "Create New Project",
        projectName: "Project Name",
        projectDescription: "Project Description",
        save: "Save",
        cancel: "Cancel",
        delete: "Delete",
        edit: "Edit",
        criteria: "Criteria",
        alternatives: "Alternatives",
        results: "Results",
        comparison: "Comparison",
        addCriteria: "Add Criteria",
        addAlternative: "Add Alternative",
        criteriaName: "Criteria Name",
        alternativeName: "Alternative Name",
        saveAndContinue: "Save & Continue",
        pairwiseComparison: "Pairwise Comparison",
        moreImportant: "More Important",
        lessImportant: "Less Important",
        equallyImportant: "Equally Important",
        consistencyRatio: "Consistency Ratio",
        priorityWeight: "Priority Weight",
        localWeight: "Local Weight",
        globalWeight: "Global Weight",
        rank: "Rank",
        finalResult: "Final Result",
        bestAlternative: "Best Alternative",
        totalCriteria: "Total Criteria",
        totalAlternatives: "Total Alternatives",
        status: "Status",
        draft: "Draft",
        inProgress: "In Progress",
        completed: "Completed",
        noProjects: "No projects yet. Create your first project to get started!",
        noCriteria: "No criteria added yet",
        noAlternatives: "No alternatives added yet",
        minRequired: "Minimum 2 required",
        compareCriteria: "Compare Criteria",
        compareAlternatives: "Compare Alternatives",
        selectCriteria: "Select Criteria",
        nextCriteria: "Next Criteria",
        previousCriteria: "Previous Criteria",
        calculateResults: "Calculate Results",
        viewResults: "View Results",
        backToDashboard: "Back to Dashboard",
        exportResults: "Export Results",
        chartView: "Chart View",
        tableView: "Table View",
        email: "Email",
        password: "Password",
        confirmPassword: "Confirm Password",
        loginButton: "Login",
        registerButton: "Register",
        rememberMe: "Remember Me",
        forgotPassword: "Forgot Password?",
        noAccount: "Don't have an account?",
        haveAccount: "Already have an account?",
        register: "Register",
        or: "or",
        continueWithGoogle: "Continue with Google",
        username: "Username",
        alternative: "Alternative",
        of: "of",
        isRequired: "is required",
        hasBeenCreated: "has been created",
        determineDecision: "Determine the decision problem to solve using AHP",
        exampleProject: "For example: Choosing Laptop",
        exampleDescription: "Explain the decision purpose in short",
        optional: "optional",
        project: "Project",
        projectNotFound: "Project Not Found",
        projectNotFoundDesc: "Project with id does not exist or has been deleted.",
        cannotBeEmpty: "cannot be empty",
        projectUpdated: "Project updated successfully",
        noDescription: "No Description",
        ahpSteps: "Steps of AHP",
        createdAt: "Created at",
        updatedAt: "Updated at",
        unfinished: "Unfinished",
        ready: "Ready",
        per: "Per",
        startAhp: "Start AHP Process",
        projectNamePlaceholder: "Enter project name",
        projectDescriptionPlaceholder: "Enter project description (optional)",
    switchTo: "Switch to",
        mode: "Mode",
        overview: "Overview",
        decisionSupport: "Decision Support",
        main: "Main",
        workflow: "Project Workflow",
        selectProjectFirst: "Select a project first",
        completePreviousStep: "Complete the previous step",
        backToOverview: "Back to Overview",
        inconsistent: "Comparison is inconsistent. Please reassign the values.",
        backTo: "Back to",
    },
    id: {
        settings: "Pengaturan",
        language: "Bahasa",
        theme: "Tema",
        logout: "Keluar",
        light: "Terang",
        dark: "Gelap",
        login: "Masuk",
        about: "Tentang",
        dashboard: "Dasbor",
        createAccount: "Buat Akun",
        decisionSupportSystem: "SISTEM PENDUKUNG KEPUTUSAN",
        professionalDecisionSupport: "Sistem Pendukung Keputusan Profesional Berbasis",
        analyticHierarchyProcess: "Analytic Hierarchy Process",
        goToDashboard: "Ke Dasbor",
        welcome: "Selamat Datang",
        myProjects: "Proyek Saya",
        createNewProject: "Buat Proyek Baru",
        projectName: "Nama Proyek",
        projectDescription: "Deskripsi Proyek",
        save: "Simpan",
        cancel: "Batal",
        delete: "Hapus",
        edit: "Edit",
        criteria: "Kriteria",
        alternatives: "Alternatif",
        results: "Hasil",
        comparison: "Perbandingan",
        addCriteria: "Tambah Kriteria",
        addAlternative: "Tambah Alternatif",
        criteriaName: "Nama Kriteria",
        alternativeName: "Nama Alternatif",
        saveAndContinue: "Simpan & Lanjutkan",
        pairwiseComparison: "Perbandingan Berpasangan",
        moreImportant: "Lebih Penting",
        lessImportant: "Kurang Penting",
        equallyImportant: "Sama Penting",
        consistencyRatio: "Rasio Konsistensi",
        priorityWeight: "Bobot Prioritas",
        localWeight: "Bobot Lokal",
        globalWeight: "Bobot Global",
        rank: "Peringkat",
        finalResult: "Hasil Akhir",
        bestAlternative: "Alternatif Terbaik",
        totalCriteria: "Total Kriteria",
        totalAlternatives: "Total Alternatif",
        status: "Status",
        draft: "Draf",
        inProgress: "Sedang Berlangsung",
        completed: "Selesai",
        noProjects: "Belum ada proyek. Buat proyek pertama Anda untuk memulai!",
        noCriteria: "Belum ada kriteria ditambahkan",
        noAlternatives: "Belum ada alternatif ditambahkan",
        minRequired: "Minimum 2 diperlukan",
        compareCriteria: "Bandingkan Kriteria",
        compareAlternatives: "Bandingkan Alternatif",
        selectCriteria: "Pilih Kriteria",
        nextCriteria: "Kriteria Berikutnya",
        previousCriteria: "Kriteria Sebelumnya",
        calculateResults: "Hitung Hasil",
        viewResults: "Lihat Hasil",
        backToDashboard: "Kembali ke Dasbor",
        exportResults: "Ekspor Hasil",
        chartView: "Tampilan Grafik",
        tableView: "Tampilan Tabel",
        email: "Email",
        password: "Kata Sandi",
        confirmPassword: "Konfirmasi Kata Sandi",
        loginButton: "Masuk",
        registerButton: "Daftar",
        rememberMe: "Ingat Saya",
        forgotPassword: "Lupa Kata Sandi?",
        noAccount: "Belum punya akun?",
        haveAccount: "Sudah punya akun?",
        register: "Daftar",
        or: "atau",
        continueWithGoogle: "Lanjutkan dengan Google",
        username: "Nama Pengguna",
        alternative: "Alternatif",
        of: "dari",
        isRequired: "diperlukan",
        hasBeenCreated: "telah dibuat",
        determineDecision: "Tentukan masalah keputusan yang akan diselesaikan menggunakan AHP",
        exampleProject: "Contoh: Memilih Laptop",
        exampleDescription: "Jelaskan tujuan keputusan secara singkat",
        optional: "opsional",
        project: "Proyek",
        projectNotFound: "Proyek Tidak Ditemukan",
        projectNotFoundDesc: "Proyek dengan id tersebut tidak ada atau telah dihapus.",
        cannotBeEmpty: "tidak boleh kosong",
        projectUpdated: "Proyek berhasil diperbarui",
        noDescription: "Tanpa Deskripsi",
        ahpSteps: "Langkah-Langkah AHP",
        createdAt: "Dibuat pada",
        updatedAt: "Diperbarui pada",
        unfinished: "Belum Selesai",
        ready: "Siap",
        per: "Per",
        startAhp: "Mulai Proses AHP",
        projectNamePlaceholder: "Masukkan nama proyek",
        projectDescriptionPlaceholder: "Masukkan deskripsi proyek (opsional)",
    switchTo: "Beralih ke",
        mode: "Mode",
        overview: "Ringkasan",
        decisionSupport: "Pendukung Keputusan",
        main: "Utama",
        workflow: "Alur Proyek",
        selectProjectFirst: "Pilih proyek terlebih dahulu",
        completePreviousStep: "Selesaikan langkah sebelumnya",
        backToOverview: "Kembali ke Ringkasan",
        inconsistent: "Perbandingan tidak konsisten. Silakan isi ulang nilainya.",
        backTo: "Kembali ke",
    },
};

const LanguageContext = createContext();

export function useLanguage() {
    return useContext(LanguageContext);
}

export function LanguageProvider({ children }) {
    const [language, setLanguage] = useState(() => {
        const saved = localStorage.getItem("dss_ahp_language");
        return saved || "en";
    });

    useEffect(() => {
        localStorage.setItem("dss_ahp_language", language);
    }, [language]);

    const t = (key) => {
        return translations[language]?.[key] || translations["en"]?.[key] || key;
    };

    const changeLanguage = (lang) => {
        if (translations[lang]) {
            setLanguage(lang);
        }
    };

    return (
        <LanguageContext.Provider value={{ language, changeLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}